version: "3.8"
services:
  temanraga:
    build: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - temanraga_be:/temanraga-be/authentication/migrations
      - temanraga_be:/temanraga-be/events/migrations
      - temanraga_be:/temanraga-be/profiles/migrations
      - temanraga_be:/temanraga-be/media
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - temanraga_be:/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - temanraga
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  temanraga_be:
