version: "3.8"
services:
  temanraga:
    build: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - temanraga_be:/temanraga-be/media
  nginx:
    build: ./nginx
    volumes:
      - temanraga_be:/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - temanraga
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email agenganugrah@gmail.com -d temanraga.xyz --agree-tos

volumes:
  temanraga_be:
