# Generated by Django 4.1 on 2022-08-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('date', models.DateTimeField()),
                ('createdBy', models.CharField(max_length=225)),
            ],
        ),
    ]
